//! Command-line entrypoint for the `sc-hooks` host runtime.

mod async_bucket;
mod audit;
mod config;
mod dispatch;
mod errors;
mod events;
mod fire;
mod handlers;
mod install;
mod metadata;
mod observability;
mod resolution;
mod session;
#[cfg(test)]
mod test_support;
mod testing;
mod timeout;

use clap::{Args, Parser, Subcommand};
use log::{error, warn};
use sc_hooks_core::errors::HookError;
use sc_hooks_core::events::HookType;
use sc_hooks_core::normalization::{RuntimeProvider, normalize_runtime_dispatch};
use sc_hooks_core::session::SessionId;
use sc_hooks_sdk::manifest::{ManifestError, ManifestLoadError};
use std::io::Write;
use std::str::FromStr;

use crate::errors::CliError;

#[derive(Debug, Parser)]
#[command(name = "sc-hooks")]
#[command(about = "Universal hook dispatcher for AI-assisted development")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Debug, Subcommand)]
enum Commands {
    /// Normal execution (called by AI tool hooks)
    Run(RunArgs),

    /// Validate config + handlers + data flow
    Audit(AuditArgs),

    /// Diagnostic trigger with synthetic/real payload
    Fire(FireArgs),

    /// Generate local provider cutover config for supported agents
    Install,

    /// Show resolved configuration
    Config,

    /// List discovered plugins
    Handlers(HandlersArgs),

    /// Run compliance tests against a plugin
    Test(TestArgs),

    /// Show full exit code reference
    ExitCodes,
}

#[derive(Debug, Args)]
struct RunArgs {
    /// Hook type name
    hook: String,

    /// Optional event name
    event: Option<String>,

    /// Run only sync-mode handlers (default behavior)
    #[arg(long, conflicts_with = "async_mode")]
    sync: bool,

    /// Run only async-mode handlers
    #[arg(long = "async", conflicts_with = "sync")]
    async_mode: bool,

    /// Async bucket identifier generated by `sc-hooks install` (e.g. 10-100)
    #[arg(long, requires = "async_mode")]
    async_bucket: Option<String>,
}

impl RunArgs {
    fn mode(&self) -> sc_hooks_core::dispatch::DispatchMode {
        if self.async_mode {
            sc_hooks_core::dispatch::DispatchMode::Async
        } else {
            sc_hooks_core::dispatch::DispatchMode::Sync
        }
    }
}

#[derive(Debug, Args)]
struct FireArgs {
    /// Hook type name
    hook: String,

    /// Optional event name
    event: Option<String>,

    /// Optional JSON payload for diagnostic invocation
    #[arg(long)]
    payload: Option<String>,
}

#[derive(Debug, Args)]
struct AuditArgs {
    /// Treat unacknowledged sandbox requirements as errors
    #[arg(long)]
    strict: bool,

    /// Reset persisted session disable state before running audit
    #[arg(long)]
    reset: bool,
}

#[derive(Debug, Args)]
struct HandlersArgs {
    /// Show canonical event taxonomy by hook type
    #[arg(long)]
    events: bool,
}

#[derive(Debug, Args)]
struct TestArgs {
    /// Plugin name
    plugin: String,
}

fn main() {
    std::panic::set_hook(Box::new(|panic_info| {
        error!("internal panic: {panic_info}");
        let _ = writeln!(std::io::stderr(), "internal panic: {panic_info}");
    }));

    let outcome = std::panic::catch_unwind(run);
    match outcome {
        Ok(Ok(())) => {}
        Ok(Err(err)) => {
            error!("{err}");
            let _ = writeln!(std::io::stderr(), "{err}");
            std::process::exit(err.exit_code());
        }
        Err(_) => {
            std::process::exit(sc_hooks_core::exit_codes::INTERNAL_ERROR);
        }
    }
}

fn run() -> Result<(), CliError> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Run(args) => {
            let config = config::load_default_config()?;
            let hook_type = HookType::from_str(&args.hook)
                .map_err(|_| CliError::internal(format!("unknown hook type `{}`", args.hook)))?;
            let payload = normalize_run_payload(
                hook_type,
                args.event.as_deref(),
                read_optional_payload_from_stdin()?,
            )
            .map_err(|err| {
                let cli_err = cli_error_for_normalization(err);
                observability::emit_standard_degraded_signal(
                    &config.observability,
                    hook_type.as_str(),
                    args.event.as_deref(),
                    args.mode(),
                    "provider_normalization",
                    &cli_err,
                );
                if let Ok(project_root) = metadata::current_project_root() {
                    observability::emit_full_audit_pre_dispatch_failure(
                        observability::FullAuditPreDispatchFailureArgs {
                            observability: &config.observability,
                            hook: hook_type.as_str(),
                            event: args.event.as_deref(),
                            mode: args.mode(),
                            project_root: &project_root,
                            stage: "provider_normalization",
                            err: &cli_err,
                            payload: None,
                        },
                    );
                }
                cli_err
            })?;
            let mode = args.mode();
            let audit_project_root = metadata::current_project_root().ok();
            let session_id = payload
                .session_id
                .clone()
                .or_else(metadata::current_session_id);
            let disabled_plugins = session::load_disabled_plugins(
                session_id
                    .as_ref()
                    .map(sc_hooks_core::session::SessionId::as_str),
            )?;
            let is_session_end = args.hook == "SessionEnd";

            let run_result = (|| -> Result<(), CliError> {
                if let Some(project_root) = audit_project_root.as_ref() {
                    observability::emit_full_audit_invocation_received(
                        &config.observability,
                        payload.hook_type.as_str(),
                        payload.event.as_deref(),
                        mode,
                        project_root,
                        payload.payload.as_ref(),
                    );
                }
                let handlers =
                    resolution::resolve_chain(
                        &config,
                        payload.hook_type,
                        payload.event.as_deref(),
                        mode,
                        payload.payload.as_ref(),
                        args.async_bucket.as_deref(),
                        &disabled_plugins,
                    )
                    .map_err(|err| {
                        let stage = match &err {
                            crate::errors::ResolutionError::ManifestLoadFailed {
                                source:
                                    ManifestLoadError::Manifest(
                                        ManifestError::AsyncLongRunningUnsupported,
                                    ),
                                ..
                            } => "dispatch_preflight",
                            _ => "resolution",
                        };
                        let cli_err = CliError::from(err);
                        observability::emit_standard_degraded_signal(
                            &config.observability,
                            payload.hook_type.as_str(),
                            payload.event.as_deref(),
                            mode,
                            stage,
                            &cli_err,
                        );
                        if let Some(project_root) = audit_project_root.as_ref() {
                            observability::emit_full_audit_pre_dispatch_failure(
                                observability::FullAuditPreDispatchFailureArgs {
                                    observability: &config.observability,
                                    hook: payload.hook_type.as_str(),
                                    event: payload.event.as_deref(),
                                    mode,
                                    project_root,
                                    stage,
                                    err: &cli_err,
                                    payload: payload.payload.as_ref(),
                                },
                            );
                        }
                        cli_err
                    })?;

                if handlers.is_empty() {
                    if let Some(project_root) = audit_project_root.as_ref() {
                        observability::emit_full_audit_zero_match(
                            &config.observability,
                            payload.hook_type.as_str(),
                            payload.event.as_deref(),
                            mode,
                            project_root,
                            payload.payload.as_ref(),
                        );
                    }
                    return Ok(());
                }

                match dispatch::execute_chain(
                    &handlers,
                    &config,
                    payload.hook_type,
                    payload.event.as_deref(),
                    mode,
                    payload.payload.as_ref(),
                )? {
                    dispatch::DispatchOutcome::Proceed => Ok(()),
                    dispatch::DispatchOutcome::Blocked { reason } => Err(CliError::blocked(reason)),
                }
            })();

            if is_session_end {
                session::clear_session(
                    session_id
                        .as_ref()
                        .map(sc_hooks_core::session::SessionId::as_str),
                )?;
            }
            run_result?;
        }
        Commands::Audit(args) => {
            if args.reset {
                let reset_path = session::state_path()?;
                session::clear_all_sessions()?;
                println!("reset: cleared {}", reset_path.display());
            }
            let config = config::load_default_config()?;
            let report = audit::run(
                &config,
                audit::AuditOptions {
                    strict: args.strict,
                },
            )?;
            let rendered = audit::render(&report);
            println!("{rendered}");
            if report.has_errors() {
                return Err(CliError::audit_failure(format!(
                    "audit found {} error(s). see report output above.",
                    report.errors().len()
                )));
            }
        }
        Commands::Fire(args) => {
            let payload = match args.payload.as_ref() {
                Some(raw) => Some(serde_json::from_str::<serde_json::Value>(raw).map_err(
                    |err| CliError::plugin_error_with_source("invalid --payload JSON", err),
                )?),
                None => Some(serde_json::json!({"synthetic": true, "source": "fire"})),
            };
            let rendered = fire::run_fire(
                &config::load_default_config()?,
                &args.hook,
                args.event.as_deref(),
                payload.as_ref(),
            )?;
            println!("{rendered}");
        }
        Commands::Install => {
            match config::load_default_config() {
                Ok(config) => {
                    let plan = install::write_default_settings(&config)?;
                    println!("wrote .claude/settings.json");
                    for warning in &plan.warnings {
                        warn!("warning: {warning}");
                        let _ = writeln!(std::io::stderr(), "warning: {warning}");
                    }
                }
                Err(err) => {
                    warn!("warning: skipping repo-local settings generation: {err}");
                    let _ = writeln!(
                        std::io::stderr(),
                        "warning: skipping repo-local settings generation: {err}"
                    );
                }
            }

            for provider in install::TargetProvider::all() {
                let plan = install::write_local_provider_cutover(provider).map_err(|err| {
                    CliError::internal_with_source("local provider cutover failed", err)
                })?;
                println!("wrote local {} cutover", provider.as_str());
                for warning in &plan.warnings {
                    warn!("warning: {warning}");
                    let _ = writeln!(std::io::stderr(), "warning: {warning}");
                }
            }
        }
        Commands::Config => {
            let config = config::load_default_config()?;
            let rendered = config.to_pretty_toml()?;
            println!("{rendered}");
        }
        Commands::Handlers(args) => {
            if args.events {
                println!("{}", handlers::render_events());
            } else {
                let report = handlers::discover()?;
                println!("{}", handlers::render(&report));
            }
        }
        Commands::Test(args) => {
            let report = testing::run_plugin_compliance(&args.plugin)?;
            println!("{}", report.render_text());
            if !report.passed() {
                return Err(CliError::audit_failure(format!(
                    "plugin {} failed compliance checks",
                    args.plugin
                )));
            }
        }
        Commands::ExitCodes => {
            print!("{}", sc_hooks_core::exit_codes::render_reference());
        }
    }

    Ok(())
}

fn read_optional_payload_from_stdin() -> Result<Option<serde_json::Value>, CliError> {
    use std::io::Read;

    let mut input = String::new();
    std::io::stdin()
        .read_to_string(&mut input)
        .map_err(|source| CliError::internal_with_source("failed reading stdin payload", source))?;

    if input.trim().is_empty() {
        return Ok(None);
    }

    let parsed = serde_json::from_str::<serde_json::Value>(&input)
        .map_err(|err| CliError::plugin_error_with_source("invalid JSON payload on stdin", err))?;

    Ok(Some(parsed))
}

struct PreparedRunPayload {
    hook_type: HookType,
    event: Option<String>,
    payload: Option<serde_json::Value>,
    session_id: Option<SessionId>,
}

fn normalize_run_payload(
    requested_hook: HookType,
    requested_event: Option<&str>,
    payload: Option<serde_json::Value>,
) -> Result<PreparedRunPayload, HookError> {
    let Some(raw_payload) = payload else {
        return Ok(PreparedRunPayload {
            hook_type: requested_hook,
            event: requested_event.map(str::to_string),
            payload: None,
            session_id: None,
        });
    };

    let Some(provider) = runtime_provider_from_env() else {
        let session_id = extract_session_id(&raw_payload)?;
        return Ok(PreparedRunPayload {
            hook_type: requested_hook,
            event: requested_event.map(str::to_string),
            payload: Some(raw_payload),
            session_id,
        });
    };

    let normalized = normalize_runtime_dispatch(provider, &raw_payload)?;
    if normalized.hook != requested_hook {
        return Err(HookError::invalid_context(format!(
            "provider normalization produced hook `{}` but the host requested `{}`",
            normalized.hook.as_str(),
            requested_hook.as_str()
        )));
    }
    if normalized.event.as_deref() != requested_event {
        return Err(HookError::validation(
            "event",
            format!(
                "provider normalization produced event {:?} but the host requested {:?}",
                normalized.event.as_deref(),
                requested_event
            ),
        ));
    }

    let session_id = extract_session_id(&normalized.payload)?;
    Ok(PreparedRunPayload {
        hook_type: normalized.hook,
        event: normalized.event,
        payload: Some(normalized.payload),
        session_id,
    })
}

fn runtime_provider_from_env() -> Option<RuntimeProvider> {
    match metadata::current_agent_type().as_deref() {
        Some("codex") => Some(RuntimeProvider::Codex),
        Some("gemini") => Some(RuntimeProvider::Gemini),
        _ => None,
    }
}

fn extract_session_id(payload: &serde_json::Value) -> Result<Option<SessionId>, HookError> {
    match payload
        .get("session_id")
        .and_then(serde_json::Value::as_str)
    {
        Some(value) => Ok(Some(SessionId::new(value.to_string())?)),
        None => Ok(None),
    }
}

fn cli_error_for_normalization(err: HookError) -> CliError {
    if err.normalization_recovery_hint().is_some() {
        CliError::blocked_with_source("provider runtime normalization failed", err)
    } else {
        CliError::plugin_error_with_source("provider runtime normalization failed", err)
    }
}
