//! Command-line entrypoint for the `sc-hooks` host runtime.

mod audit;
mod config;
mod dispatch;
mod errors;
mod events;
mod fire;
mod handlers;
mod install;
mod metadata;
mod observability;
mod resolution;
mod session;
#[cfg(test)]
mod test_support;
mod testing;
mod timeout;

use clap::{Args, Parser, Subcommand};
use log::{error, warn};
use sc_hooks_sdk::manifest::{ManifestError, ManifestLoadError};
use std::io::Write;

use crate::errors::CliError;

#[derive(Debug, Parser)]
#[command(name = "sc-hooks")]
#[command(about = "Universal hook dispatcher for AI-assisted development")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Debug, Subcommand)]
enum Commands {
    /// Normal execution (called by AI tool hooks)
    Run(RunArgs),

    /// Validate config + handlers + data flow
    Audit(AuditArgs),

    /// Diagnostic trigger with synthetic/real payload
    Fire(FireArgs),

    /// Generate .claude/settings.json hook entries
    Install,

    /// Show resolved configuration
    Config,

    /// List discovered plugins
    Handlers(HandlersArgs),

    /// Run compliance tests against a plugin
    Test(TestArgs),

    /// Show full exit code reference
    ExitCodes,
}

#[derive(Debug, Args)]
struct RunArgs {
    /// Hook type name
    hook: String,

    /// Optional event name
    event: Option<String>,

    /// Run only sync-mode handlers (default behavior)
    #[arg(long, conflicts_with = "async_mode")]
    sync: bool,

    /// Run only async-mode handlers
    #[arg(long = "async", conflicts_with = "sync")]
    async_mode: bool,

    /// Async bucket identifier generated by `sc-hooks install` (e.g. 10-100)
    #[arg(long, requires = "async_mode")]
    async_bucket: Option<String>,
}

impl RunArgs {
    fn mode(&self) -> sc_hooks_core::dispatch::DispatchMode {
        if self.async_mode {
            sc_hooks_core::dispatch::DispatchMode::Async
        } else {
            sc_hooks_core::dispatch::DispatchMode::Sync
        }
    }
}

#[derive(Debug, Args)]
struct FireArgs {
    /// Hook type name
    hook: String,

    /// Optional event name
    event: Option<String>,

    /// Optional JSON payload for diagnostic invocation
    #[arg(long)]
    payload: Option<String>,
}

#[derive(Debug, Args)]
struct AuditArgs {
    /// Treat unacknowledged sandbox requirements as errors
    #[arg(long)]
    strict: bool,

    /// Reset persisted session disable state before running audit
    #[arg(long)]
    reset: bool,
}

#[derive(Debug, Args)]
struct HandlersArgs {
    /// Show canonical event taxonomy by hook type
    #[arg(long)]
    events: bool,
}

#[derive(Debug, Args)]
struct TestArgs {
    /// Plugin name
    plugin: String,
}

fn main() {
    std::panic::set_hook(Box::new(|panic_info| {
        error!("internal panic: {panic_info}");
        let _ = writeln!(std::io::stderr(), "internal panic: {panic_info}");
    }));

    let outcome = std::panic::catch_unwind(run);
    match outcome {
        Ok(Ok(())) => {}
        Ok(Err(err)) => {
            error!("{err}");
            let _ = writeln!(std::io::stderr(), "{err}");
            std::process::exit(err.exit_code());
        }
        Err(_) => {
            std::process::exit(sc_hooks_core::exit_codes::INTERNAL_ERROR);
        }
    }
}

fn run() -> Result<(), CliError> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Run(args) => {
            let config = config::load_default_config()?;
            let payload = read_optional_payload_from_stdin()?;
            let mode = args.mode();
            let session_id = metadata::current_session_id();
            let disabled_plugins = session::load_disabled_plugins(
                session_id
                    .as_ref()
                    .map(sc_hooks_core::session::SessionId::as_str),
            )?;
            let is_session_end = args.hook == "SessionEnd";

            let run_result = (|| -> Result<(), CliError> {
                let handlers =
                    resolution::resolve_chain(
                        &config,
                        &args.hook,
                        args.event.as_deref(),
                        mode,
                        payload.as_ref(),
                        args.async_bucket.as_deref(),
                        &disabled_plugins,
                    )
                    .map_err(|err| {
                        let stage = match &err {
                            crate::errors::ResolutionError::ManifestLoadFailed {
                                source:
                                    ManifestLoadError::Manifest(
                                        ManifestError::AsyncLongRunningUnsupported,
                                    ),
                                ..
                            } => "dispatch_preflight",
                            _ => "resolution",
                        };
                        let cli_err = CliError::from(err);
                        observability::emit_standard_degraded_signal(
                            &config.observability,
                            &args.hook,
                            args.event.as_deref(),
                            mode,
                            stage,
                            &cli_err,
                        );
                        cli_err
                    })?;

                if handlers.is_empty() {
                    return Ok(());
                }

                match dispatch::execute_chain(
                    &handlers,
                    &config,
                    &args.hook,
                    args.event.as_deref(),
                    mode,
                    payload.as_ref(),
                )? {
                    dispatch::DispatchOutcome::Proceed => Ok(()),
                    dispatch::DispatchOutcome::Blocked { reason } => Err(CliError::blocked(reason)),
                }
            })();

            if is_session_end {
                session::clear_session(
                    session_id
                        .as_ref()
                        .map(sc_hooks_core::session::SessionId::as_str),
                )?;
            }
            run_result?;
        }
        Commands::Audit(args) => {
            if args.reset {
                let reset_path = session::state_path()?;
                session::clear_all_sessions()?;
                println!("reset: cleared {}", reset_path.display());
            }
            let config = config::load_default_config()?;
            let report = audit::run(
                &config,
                audit::AuditOptions {
                    strict: args.strict,
                },
            )?;
            let rendered = audit::render(&report);
            println!("{rendered}");
            if report.has_errors() {
                return Err(CliError::audit_failure(format!(
                    "audit found {} error(s). see report output above.",
                    report.errors.len()
                )));
            }
        }
        Commands::Fire(args) => {
            let payload = match args.payload.as_ref() {
                Some(raw) => Some(serde_json::from_str::<serde_json::Value>(raw).map_err(
                    |err| CliError::plugin_error_with_source("invalid --payload JSON", err),
                )?),
                None => Some(serde_json::json!({"synthetic": true, "source": "fire"})),
            };
            let rendered = fire::run_fire(
                &config::load_default_config()?,
                &args.hook,
                args.event.as_deref(),
                payload.as_ref(),
            )?;
            println!("{rendered}");
        }
        Commands::Install => {
            let config = config::load_default_config()?;
            let plan = install::write_default_settings(&config)?;
            println!("wrote .claude/settings.json");
            for warning in &plan.warnings {
                warn!("warning: {warning}");
                let _ = writeln!(std::io::stderr(), "warning: {warning}");
            }
        }
        Commands::Config => {
            let config = config::load_default_config()?;
            let rendered = config.to_pretty_toml()?;
            println!("{rendered}");
        }
        Commands::Handlers(args) => {
            if args.events {
                println!("{}", handlers::render_events());
            } else {
                let report = handlers::discover()?;
                println!("{}", handlers::render(&report));
            }
        }
        Commands::Test(args) => {
            let report = testing::run_plugin_compliance(&args.plugin)?;
            println!("{}", report.render_text());
            if !report.passed() {
                return Err(CliError::audit_failure(format!(
                    "plugin {} failed compliance checks",
                    args.plugin
                )));
            }
        }
        Commands::ExitCodes => {
            print!("{}", sc_hooks_core::exit_codes::render_reference());
        }
    }

    Ok(())
}

fn read_optional_payload_from_stdin() -> Result<Option<serde_json::Value>, CliError> {
    use std::io::Read;

    let mut input = String::new();
    std::io::stdin()
        .read_to_string(&mut input)
        .map_err(|source| CliError::internal_with_source("failed reading stdin payload", source))?;

    if input.trim().is_empty() {
        return Ok(None);
    }

    let parsed = serde_json::from_str::<serde_json::Value>(&input)
        .map_err(|err| CliError::plugin_error_with_source("invalid JSON payload on stdin", err))?;

    Ok(Some(parsed))
}
